name: Build SOMEIP Feeder Docker Image

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'someip-feeder/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'someip-feeder/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 1y2u3i/testenter/someip-feeder

jobs:
  build-and-push:
    name: "Building SOME/IP Feeder image for ARM64"
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: "recursive"

    - name: Set execute permissions for build-release.sh
      run: chmod +x ./build-release.sh

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=arm64-latest
          type=raw,value=feeders-v4

    

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./someip-feeder
        file: ./someip-feeder/Dockerfile
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max